### PR TITLE
Create he.js

### PR DESCRIPTION
**Pull request by Uziel302**

### CODE REVIEW

**Comment by Joeytje50** [comment]
In order to work, the new language file will need to be added to i18n.js itself as well (under the comment `// List all languages here:`). If you can add that I'll merge both changes to master and make the changes to the live JWB as well.

**Comment by Uziel302** [comment]
Done that long ago, how shall we proceed?

**Comment by Rexogamer** [comment]
I think having all the changes in one PR would help (cherrypick the commit from the other branch, then close the other PR).

**Comment by Uziel302** [comment]
> I think having all the changes in one PR would help (cherrypick the commit from the other branch, then close the other PR).

Done

**Comment by Joeytje50** [comment]
Although I don't know any Hebrew, the format looks good, so I'll merge it and deploy it to the live JWB script as well.

**Comment by Uziel302** [comment]
Now I need explanation how to use the file because just switching to the main project i18n file switches the language to english

**Comment by Joeytje50** [comment]
Apologies, that was another bug unrelated to the addition of the Hebrew i18n file. This issue should be resolved now. I will update the github repo momentarily.

**Comment by Uziel302** [comment]
This change made me get English.
https://he.wikipedia.org/w/index.php?title=%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9:Uziel302/JWB.js&diff=32167711&oldid=31885572
How should I make it work?

**Pull request merged**
